name-template: 'v$RESOLVED_VERSION 🥓'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    collapse-after: 5
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    collapse-after: 5
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    collapse-after: 5
    label: 'chore'
category-template: '### $TITLE'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
replacers:
  - search: '/TEST-(\d{4,})/g'
    replace: '[TEST-$1](https://testing.atlassian.net/browse/TEST-$1)'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
